version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "16:05"
      timezone: "Asia/Tehran"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"
